### ISSUE TITLE
スキーマに従って必要な情報が格納されているJSONを返すサーバ機能をServer Side APIに組み込む

### ISSUE THREAD

**Issue by Gaku-Kunimi** [cloudnativedaysjp/emtec-intermission#20]
dk を使うイベント以外でもインタミを使えるようにする

- 悩みそうな点
  - プロフィール画像がない場合
    - トラックごとの A B C D とかを丸く出すとかで置き換えてもいい気がする
  - セッション情報のスキーマをどうするか
    - 少々項目数が多いですが、一旦 CND と同じ項目数の JSON を想定してもいい気がしています。後から追加する方が面倒なので

**Comment by hrk091** [comment]
@Gaku-Kunimi 
要件の確認をさせてください。

- JSONをリアルタイムに差し替えて、インタミの描画に反映する、ということをやりたかったりしますでしょうか？もしくは、更新の都度ビルド&デプロイ必須でも問題ないでしょうか？
- Server Side APIに組み込む、となっていますが、SSG(Static Site Generation)でpageをrenderingしてしまって問題ないと思っています。これでも良いでしょうか？
  - なお、SSGを選択しても、JSONを差し替えたときにコンテンツを動的に差し替えることはNextjsの機能で実現可能なので、上記2つは独立して考えて大丈夫です。
  - インタミ以外からもAPI callしたい、というようなことがあればAPI化した方が良い（その場合は、そもそもNextJSのServer sideではなく独立したサービスにしたほうが良さそうですが）と思いますが、そうでないならAPI化は不要な認識です
  
あと、コメント頂いている懸念事項については以下で進めようと思います。

- プロフィール画像
  - プロフィール画像もJSONに持たせるようにし、それがない場合は `トラックごとの A B C D とかを丸く出す` にfallbackするようにします。
- セッション情報のスキーマ
  - インタミで使っている情報に限定したスキーマにします。

**Comment by hrk091** [comment]
なお、今回のタイミングでAppRouterに切り替える予定です。
dk向けにPagesRouter側の実装も残します（CNDT2024に間に合わなかったときの保険）が、いずれはdkもAppRouter側に寄せるつもりで進めます。

**Comment by Gaku-Kunimi** [comment]
検討ありがとうございます、大変遅くなりました

> JSONをリアルタイムに差し替えて、インタミの描画に反映する、ということをやりたかったりしますでしょうか？もしくは、更新の都度ビルド&デプロイ必須でも問題ないでしょうか？

リアルタイムの差し替えは必須ではないなと思ったので、更新の都度 ビルド＆デプロイ 必須で問題ありません!  セッション情報が変わることは基本的にないか、あった場合でもビルドする隙はあるはずなので

> Server Side APIに組み込む、となっていますが、SSG(Static Site Generation)でpageをrenderingしてしまって問題ないと思っています。これでも良いでしょうか？

上記と同様こちらも問題ありません (それぞれ独立して考えられるんですね)

> インタミ以外からもAPI callしたい、というようなことがあればAPI化した方が良い（その場合は、そもそもNextJSのServer sideではなく独立したサービスにしたほうが良さそうですが）と思いますが、そうでないならAPI化は不要な認識です

インタミ以外から API call することは予定していないですね


懸念事項についても、検討ありがとうございます。 方針についてそちらで問題ありません!
